### ISSUE TITLE
Regarding the paper EMNLP 2021 CPFT

### ISSUE THREAD

**Issue by hdzhang-code** [Doragd/Doragd#2]
Hi, Doragd,

I find you because it seems you have also encountered the same issue: you cannot find the code of EMNLP 2021 paper "Few-Shot Intent Detection via Contrastive Pre-Training and Fine-Tuning": https://github.com/jianguoz/Few-Shot-Intent-Detection/issues/1

I have tried to reproduce the results (CPFT), but I failed. The reproduced result is notably lower than in the paper. 

Have you ever tried to reproduce it, or produce some results that is comparable to that in the paper?

Best Regards,
Neil

**Comment by Doragd** [comment]
Hi, Zhang,
Sorry, I do not try to reproduce the results because the code is not released.
I read your paper called CL-Reg a few days ago and checked the details. The evaluation way is different from the CPFT, which adopts the standard few-shot setting while CL-Reg adopts the N-way K-shot evaluation.
I do not know if it is the reason for the difference in performance.

**Comment by hdzhang-code** [comment]
Well, how do you know my name, from "hdzhang-code"

**Comment by hdzhang-code** [comment]
The evaluation way surely contributes to the difference. However, in that paper CL-Reg and Cor-Reg, I try to make a fair comparison by aligning the evaluation among all methods.

Recently, I try to make a more comprehensive and solid comparison between methods. I am also trying to align the context for comparison but it is another context. However, there is a confusing, frustrating and large gap between my results and CPFT, which I cannot explain. Maybe there is some critical training details such as accumulate steps that make much difference?

**Comment by hdzhang-code** [comment]
BTW, transformer version, in my experience, is also a key factor that contributes to the difference.

**Comment by Doragd** [comment]
Personally, I don't think the accumulation of steps makes much difference. I think it's really valuable to explore the reasons for the huge gap. Sorry, I can't be of more help to you.
No offense. I can see from your report that you are the author of IntentBERT.
